# Generated by Django 3.2.9 on 2021-11-13 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stage',
            new_name='Solution_Stage',
        ),
    ]
