# Generated by Django 3.2.9 on 2021-11-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_stage_solution_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution_stage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='solution_stage',
            name='title',
        ),
        migrations.AddField(
            model_name='solution_stage',
            name='s_number',
            field=models.CharField(choices=[('1_Commencement', 'One'), ('2_Data_Cleaning', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six')], default='1_Commencement', max_length=30),
        ),
    ]
