# Generated by Django 3.2.9 on 2021-11-15 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211114_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution_stage',
            name='belongs_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.problem'),
        ),
        migrations.AlterField(
            model_name='solution_stage',
            name='isActivated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='solution_stage',
            name='s_number',
            field=models.CharField(choices=[('One', 'One'), ('2_Data_Cleaning', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six')], default='One', max_length=30),
        ),
        migrations.AlterField(
            model_name='solution_stage',
            name='state',
            field=models.CharField(choices=[('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green')], default='GREEN', max_length=6),
        ),
    ]
