# Generated by Django 3.2.9 on 2021-11-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211115_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_link',
            field=models.URLField(default='https://docs.google.com/document/d/1ZVbLLNmL3h5gdxOO1oTnSguBiw37y0KTnOfRvNyLRx8/edit?usp=sharing'),
        ),
        migrations.AlterField(
            model_name='solution_stage',
            name='s_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1. Data Acuisition'), (2, '2. Data Cleaning and Reorganisation'), (3, '3. Data visualization and initial feature assessment'), (4, '4. Data Modelling'), (5, '5. Results and Conclusions')], default=1),
        ),
        migrations.AlterField(
            model_name='solution_stage',
            name='state',
            field=models.CharField(choices=[('RED', 'red'), ('YELLOW', 'yellow'), ('GREEN', 'green')], default='GREEN', max_length=6),
        ),
    ]
