# Generated by Django 3.2.9 on 2021-11-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_solution_stage_s_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution_stage',
            name='s_number',
            field=models.IntegerField(choices=[(1, '1. Data Acquisition'), (2, '2. Data Cleaning and Reorganisation'), (3, '3. Data visualization and initial feature assessment'), (4, '4. Data Modelling'), (5, '5. Results and Conclusions')], default=1),
        ),
    ]
