# Generated by Django 3.2.9 on 2021-12-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_solution_stage_s_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution_stage',
            name='state',
            field=models.CharField(choices=[('RED', 'red'), ('YELLOW', 'yellow'), ('GREEN', 'green')], default='YELLOW', max_length=6),
        ),
    ]
